### ISSUE TITLE
Paused

### ISSUE THREAD

**Issue by Houtaro001** [osamahamad/payout-targets-data#1]
Good day. Thank you for your work, it's a really good idea. However, why is it not working anymore? If it is paused indefinitely, could you please send me the script you used to automate this repository?

Regards

**Comment by osamahamad** [comment]
Sorry, the process got paused because I was running it on a Docker container via a cron job. During some maintenance work on other tasks, I had to restart the container, which caused the cron job status to be marked as stopped. It should be working again now.

regarding the script, I think it should ideally run on a GitHub Action instead of my server. However, I want to integrate the results directly with other tools and processes through the script. The script is currently hardcoded, but I plan to publish it after some modifications. There's a high possibility that I will transition it to run on a github action in the future.

**Comment by Houtaro001** [comment]
Again, thank you for your great work. It's now working fine
